export const SIGN_IN_REQUEST = "SIGN_IN_REQUEST";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILED = "SIGN_IN_FAILED";

export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILED = "SIGN_UP_FAILED";
export const SIGN_UP_VALID_FAILED = "SIGN_UP_VALID_FAILED";
export const SIGN_UP_MODAL_CLOSE = "SIGN_UP_MODAL_CLOSE";

// 
export const CHANGE_CALLENDAR_OWNER = "CHANGE_CALLENDAR_OWNER";
export const GET_OVERVIEW_SUCCESS = "GET_OVERVIEW_SUCCESS";
